#!/bin/sh

cat misc/README.pre.md > docs/README.md
./gen.readme.py >> docs/README.md
cat misc/README.suf.md >> docs/README.md

cat misc/README.pre.md > README.md
./gen.readme.py docs/ >> README.md
cat misc/README.suf.md >> README.md

git add README.md docs/README.md
